MIN_ROTATION: float = -45.0
MAX_ROTATION: float = 45.0

MIN_EXTENSION: float = 0.0
MAX_EXTENSION: float = 0.55 
#MAX_EXTENSION: float = 0.6096 # robot cad

MIN_ELEVATION: float = 0.0
MAX_ELEVATION: float = 0.25
#MAX_ELEVATION: float = 0.2667 # robot cad

PIVOT_DEPTH_IN_NET: float = 0.1651

MIN_EXTENSION_THRESHOLD: float = 1.0
MAX_EXTENSION_THRESHOLD: float = 3.0
PUCK_DISTANCE_TO_EXTENSION_RATIO: float = MAX_EXTENSION_THRESHOLD / (MAX_EXTENSION_THRESHOLD - MIN_EXTENSION_THRESHOLD)

BUTTERFLY_DISTANCE_THRESHOLD: float = 2.0 # m
BUTTERFLY_HEIGHT_THRESHOLD: float = 0.4 # m
MIN_ELEVATION_THRESHOLD: float = 0.5
MAX_ELEVATION_THRESHOLD: float = 1.0
PUCK_HEIGHT_TO_ELEVATION_RATIO: float = MAX_ELEVATION_THRESHOLD / (MAX_ELEVATION_THRESHOLD - MIN_ELEVATION_THRESHOLD)

NEUTRAL_POSITION: tuple[float, float, float] = (0.0, MAX_EXTENSION / 2.0, MAX_ELEVATION / 2.0) # (rotation, extension, elevation)

DRIFT_TO_NEUTRAL_MAX_POWER: int = 63
INCONSISTENT_POSITION_MAX_POWER: int = 63
REGULAR_MAX_POWER: int = 255